image: ruby:2.7.2

cache:
  paths:
    - node_modules
    - vendor

variables:
  BUNDLE_DEPLOYMENT: "true"
  BUNDLE_FROZEN: "true"
  DEBIAN_FRONTEND: "noninteractive"
  NO_CONTRACTS: "true"

before_script:
  - curl -sL https://deb.nodesource.com/setup_15.x | bash -
  - apt-get update -qq
  - apt-get install -qq -y apt-utils
  - apt-get upgrade -qq -y
  - apt-get install -qq -y nodejs
  - ruby --version
  - bundle --version
  - node --version
  - npm --version
  - ./bin/setup

build:
  stage: build
  script:
  - bundle exec middleman build --build-dir=build
  artifacts:
    paths:
    - build
  except:
  - main
  - master

pages:
  stage: deploy
  script:
  - bundle exec middleman build
  artifacts:
    paths:
    - public
  only:
  - main
  - master
