# .gitlab-ci.yml - See https://docs.gitlab.com/ee/ci/yaml

variables:
  GIT_DEPTH: "3"
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build
  - lint
  - test
  - generate
  - deploy

.hugo:
  # Hugo container images in GitLab Container Registry: https://gitlab.com/pages/hugo/container_registry
  # image: registry.gitlab.com/pages/hugo:latest
  # Hugo container image including Node.js for the webpacker asset pipeline
  image:
    name: klakegg/hugo:ext-alpine
    entrypoint: [""]
  cache:
    paths:
      - node_modules
  script:
    - rm -rf public/
    - npm install
    - rm -rf public/
    - NODE_ENV=production hugo --verbose --gc --minify
    - ./bin/compress-public
  artifacts:
    paths:
      - public

hugo:
  extends: .hugo
  stage: test
  except:
    - main
    - master

pages:
  extends: .hugo
  stage: generate
  environment:
    name: Gitlab Pages
    url: https://quatauta.gitlab.io/
  only:
    - main
    - master

eslint:
  stage: lint
  image: pipelinecomponents/eslint:latest
  before_script:
    - touch dummy.js
  script:
    - eslint $( [[ -e .eslintrc ]] || echo '--no-eslintrc' ) --color .

markdownlint:
  stage: lint
  image:
    name: thegeeklab/markdownlint-cli:latest
    entrypoint: ["/bin/ash", "-c"]
  script:
    - markdownlint-cli .

stylelint:
  stage: lint
  image: pipelinecomponents/stylelint:latest
  script:
    - stylelint --color '**/*.css'
  allow_failure: true

yamllint:
  stage: lint
  image:
    name: cytopia/yamllint:latest
    entrypoint: ["/bin/ash", "-c"]
  script:
    - yamllint -f colored .
