image: ruby:2.7.2

#cache:
#  paths:
#    - node_modules
#    - vendor

variables:
  BUNDLE_DEPLOYMENT: "true"
  BUNDLE_FROZEN: "true"
  DEBIAN_FRONTEND: "noninteractive"
  NO_CONTRACTS: "true"
  RUBY_NODEJS_IMAGE: "${CI_REGISTRY_IMAGE}/ruby-nodejs:${CI_COMMIT_REF_SLUG}"

ruby_nodejs:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}\n' "${CI_REGISTRY}" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" > /kaniko/.docker/config.json
    - echo "${RUBY_NODEJS_IMAGE}"
    - /kaniko/executor --cache --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${RUBY_NODEJS_IMAGE}"

test_build:
  stage: test
  image: ${RUBY_NODEJS_IMAGE}
  script:
    - ruby --version
    - bundle --version
    - node --version
    - npm --version
    - ./bin/setup
    - bundle exec middleman build --build-dir=build
  artifacts:
    paths:
    - build
  cache:
    paths:
      - node_modules
      - vendor
  except:
  - main
  - master

pages:
  stage: deploy
  script:
    - ruby --version
    - bundle --version
    - node --version
    - npm --version
    - ./bin/setup
    - bundle exec middleman build
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
      - vendor
  only:
  - main
  - master
