image: ruby:2.7.2

variables:
  BUNDLE_DEPLOYMENT: "true"
  BUNDLE_FROZEN: "true"
  DEBIAN_FRONTEND: "noninteractive"
  NO_CONTRACTS: "true"
  RUBY_NODEJS_IMAGE: "${CI_REGISTRY_IMAGE}/ruby-nodejs:${CI_COMMIT_REF_SLUG}"

ruby_nodejs:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}\n' "${CI_REGISTRY}" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${RUBY_NODEJS_IMAGE}"

.middleman:
  image: ${RUBY_NODEJS_IMAGE}
  before_script:
    - ruby --version
    - bundle --version
    - node --version
    - npm --version
    - ./bin/setup
  cache:
    paths:
      - node_modules
      - vendor

test_build:
  extends: .middleman
  stage: test
  script:
    - bundle exec middleman build --build-dir=build
  artifacts:
    paths:
      - build
  except:
    - main
    - master

pages:
  stage: test
  extends: .middleman
  script:
    - bundle exec middleman build
  artifacts:
    paths:
      - public
  environment:
    name: pages
    url: https://quatauta.gitlab.io/
  only:
    - main
    - master
